version: '3.4'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    volumes:
        - ./seq:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    ports:
      - 5341:80
    networks:
      - the-template-network

networks: 
  the-template-network:
    external: true
